package com.sdd.mapoverlay;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;
import java.util.Stack;

import com.sdd.mapoverlay.utils.Logs;
import com.sdd.mapoverlay.utils.Segment;
import com.sdd.mapoverlay.utils.Store;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.SelectionMode;

public class SegmentsListController implements Initializable {
    public ScrollPane segmentsList;
    public Button deleteButton;
    public Button undoButton;
    public ListView<Segment> segmentsListView;
    public static Stack<Logs> logsHistory = SidePanelController.logsHistory;

    public void setSegmentsList(List<Segment> segments) {
        segmentsListView.getItems().clear();
        for (Segment segment : segments) {
            segmentsListView.getItems().add(segment);
        }
    }

    @FXML
    protected void onDeleteButtonClick() {
        Segment segment = segmentsListView.getSelectionModel().getSelectedItem();
        if (segment != null) {
            segmentsListView.getItems().remove(segment);
            logsHistory.push(new Logs(segment, "DEL"));
            undoButton.setDisable(logsHistory.isEmpty());
            
            Store.getRootController().removeSegment(segment);
        }
    }

    @FXML
    protected void onUndoButtonClick() {

        if (!(logsHistory.isEmpty())) {
            Logs topLog = logsHistory.pop();
            if (logsHistory.isEmpty()) {
                undoButton.setDisable(true);
            }
            switch (topLog.getType()) {
                case "ADD":
                    System.out.println(segmentsListView.getItems().remove(topLog.getSegment()));
                    Store.getRootController().removeSegment(topLog.getSegment());
                    break;
                case "DEL":
                default:
                /* Since the type of log is generated by the machine, there shouldn't be any other case than "ADD" or "DEL" */
                    Store.getRootController().addSegment(topLog.getSegment());
                    segmentsListView.getItems().add(topLog.getSegment());
                    break;
            }
        } else {
            //TODO : create error message
        }
    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        segmentsListView.getSelectionModel().setSelectionMode(SelectionMode.SINGLE);
        List<Segment> segments = Store.getRootController().getChartContent();

        segmentsListView.getItems().addAll(segments);

        segmentsListView.getSelectionModel().selectedItemProperty().addListener((observable, oldValue, newValue) -> {
            // Change the strike color of the newValue (Segment) in the chart to orange
            Store.getRootController().highlightSegment(newValue);
            deleteButton.setDisable(newValue == null);
        });
        undoButton.setDisable(logsHistory.isEmpty());

    }
}
